// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Surrounder
{
    internal sealed partial class Vsix
    {
        public const string Id = "Surrounder.8cbb0f4d-2348-463a-aa72-a5b4a62ac4ba";
        public const string Name = "Surrounder";
        public const string Description = @"Surrounds any selected texts with matching quotation or brace pairs";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "quote, brace, pairs, selection";
    }
}
